"""Disconnected execution and a narrow host-owned robot relay."""

import json
import os
import re
import shutil
import signal
import socketserver
import subprocess
import tempfile
import threading
import time
import uuid
from pathlib import Path
from typing import Any, Protocol

from pydantic import BaseModel, ConfigDict, Field

from .types import GeneratedLibrary, OptionContract


class HostBridge(Protocol):
    """Actual robot observations and bounded low-level actions; never a reset API."""

    def observe(self) -> dict[str, Any]: ...

    def step(self, *, action: dict[str, Any] | list[Any]) -> dict[str, Any]: ...

    def action_spec(self) -> dict[str, Any]: ...


class SandboxSettings(BaseModel):
    """Trusted, explicit runtime locations; neither is generated by the learner."""

    model_config = ConfigDict(extra="forbid", frozen=True)
    image: str = Field(min_length=1)
    robocode_checkout: Path
    container_python: str = "/opt/robocode-strict/bin/python"
    timeout_seconds: float = Field(default=120, gt=0)
    artifact_dir: Path = Path("artifacts/agentic-runtime")
    seed: int = Field(default=0, ge=0)
    memory_mb: int = Field(default=4096, ge=256)
    cpus: float = Field(default=2, gt=0)

    def transport_source(self) -> Path:
        source = self.robocode_checkout / "src/robocode/utils/isolated_transport.py"
        if not source.is_file():
            raise RuntimeError("Robocode checkout lacks the disconnected runtime supervisor")
        text = source.read_text()
        if "def verify_namespace(" not in text or "def verify_strict_runtime(" not in text:
            raise RuntimeError("Robocode supervisor lacks required isolation checks")
        return source


class PolicyExecution(BaseModel):
    """Controller completion is distinct from visually judged skill success."""

    steps: int = Field(ge=0)
    controller_done: bool
    final_observation: dict[str, Any]
    trajectory_path: str
    error: str | None = None
    seed: int = 0


class DockerContainer:
    """One local, resource-bounded container with no network or host credentials."""

    def __init__(self, *, settings: SandboxSettings) -> None:
        self.settings = settings

    @staticmethod
    def client() -> list[str]:
        if shutil.which("docker") is None:
            raise RuntimeError("Docker is required; generated policies never run on the host")
        return ["docker", "--host", "unix:///var/run/docker.sock"]

    def image_id(self) -> str:
        result = subprocess.run(
            [*self.client(), "image", "inspect", "--format", "{{.Id}}", self.settings.image],
            capture_output=True,
            text=True,
            timeout=30,
            check=True,
        )
        image = result.stdout.strip()
        if not re.fullmatch(r"sha256:[0-9a-f]{64}", image):
            raise RuntimeError("Docker did not return an immutable image ID")
        return image

    def command(
        self,
        *,
        name: str,
        work_dir: Path,
        argv: list[str],
        writable: bool = False,
        mounts: tuple[tuple[Path, str, bool], ...] = (),
        environment: dict[str, str] | None = None,
    ) -> list[str]:
        if os.getuid() == 0:
            raise RuntimeError("Run the experiment as a non-root host user")
        command = [
            *self.client(),
            "run",
            "--rm",
            "--init",
            "-i",
            "--pull",
            "never",
            "--name",
            name,
            "--network",
            "none",
            "--cap-drop",
            "ALL",
            "--security-opt",
            "no-new-privileges",
            "--read-only",
            "--user",
            f"{os.getuid()}:{os.getgid()}",
            "--memory",
            f"{self.settings.memory_mb}m",
            "--memory-swap",
            f"{self.settings.memory_mb}m",
            "--cpus",
            str(self.settings.cpus),
            "--pids-limit",
            "256",
            "--tmpfs",
            "/tmp:rw,nosuid,nodev,size=256m",
            "--tmpfs",
            f"/home/node:rw,nosuid,nodev,size=128m,uid={os.getuid()},gid={os.getgid()}",
            "--workdir",
            "/sandbox",
            "--entrypoint",
            self.settings.container_python,
        ]
        for source, destination, readonly in ((work_dir, "/sandbox", not writable), *mounts):
            if any(character in str(source) + destination for character in (",", "\n")):
                raise ValueError("Docker mount paths cannot contain separators")
            command += [
                "--mount",
                f"type=bind,src={source.resolve()},dst={destination}"
                + (",readonly" if readonly else ""),
            ]
        for key, value in (environment or {}).items():
            command += ["--env", f"{key}={value}"]
        return [*command, self.image_id(), *argv]

    def remove(self, *, name: str) -> None:
        # Killing the Docker client does not stop its container. Always clean up
        # by the unique name, including startup failures and budget cancellation.
        subprocess.run(
            [*self.client(), "rm", "--force", name],
            stdout=subprocess.DEVNULL,
            stderr=subprocess.DEVNULL,
            timeout=30,
            check=False,
        )


class DockerPolicyExecutor:
    """Load generated Python only after Robocode verifies the strict namespace."""

    def __init__(self, *, settings: SandboxSettings) -> None:
        self.settings = settings
        self.container = DockerContainer(settings=settings)

    def command(self, *, work_dir: Path, name: str) -> list[str]:
        return self.container.command(
            name=name,
            work_dir=work_dir,
            argv=[
                "/sandbox/transport.py",
                "/sandbox/transport.json",
                self.settings.container_python,
                "/sandbox/policy_worker.py",
            ],
        )

    def execute(
        self, *, library: GeneratedLibrary, option: OptionContract, bridge: HostBridge
    ) -> PolicyExecution:
        if option.controller is None:
            raise ValueError("Human interventions must use the trusted human mechanism")
        if option not in library.manifest.options:
            raise ValueError("Option must belong to the frozen library")
        supervisor = self.settings.transport_source()
        self.settings.artifact_dir.mkdir(parents=True, exist_ok=True)
        trajectory = (self.settings.artifact_dir / f"trajectory-{uuid.uuid4().hex}.jsonl").resolve()
        with tempfile.TemporaryDirectory(prefix="hitl-policy-") as tmp:
            work = Path(tmp)
            shutil.copyfile(supervisor, work / "transport.py")
            shutil.copyfile(Path(__file__).with_name("policy_worker.py"), work / "policy_worker.py")
            (work / "transport.json").write_text(
                json.dumps({"listeners": [], "strict_blackbox": True})
            )
            (work / "request.json").write_text(
                json.dumps({
                    "controller": option.controller,
                    "parameters": option.parameters,
                    "max_steps": option.max_steps,
                    "seed": self.settings.seed,
                })
            )
            for name, source in library.controllers.items():
                target = work / "controllers" / name
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_text(source)
            relay = RobotRelay(
                path=work / "robot.sock",
                bridge=bridge,
                max_steps=option.max_steps,
                trajectory_path=trajectory,
            )
            try:
                error = self._run(work=work, relay=relay)
                if not relay.finished and not relay.started:
                    raise RuntimeError("Policy worker exited without an authenticated completion")
                if not relay.finished and error is None:
                    error = "Generated policy exited without completing its option"
                final_observation = bridge.observe()
                relay.record_final(observation=final_observation, error=error)
                return PolicyExecution(
                    steps=relay.steps,
                    controller_done=relay.done and error is None and relay.error is None,
                    final_observation=final_observation,
                    trajectory_path=str(trajectory),
                    error=error or relay.error,
                    seed=self.settings.seed,
                )
            finally:
                relay.server_close()

    def _run(self, *, work: Path, relay: "RobotRelay") -> str | None:
        # Native renderers own thread-affine contexts. Service the robot on the
        # caller's thread while the sandbox runs separately, never in a relay thread.
        relay.timeout = 0.05
        deadline = time.monotonic() + self.settings.timeout_seconds
        name = f"hitl-policy-{uuid.uuid4().hex}"
        with (
            tempfile.TemporaryFile(mode="w+") as output,
            tempfile.TemporaryFile(mode="w+") as error,
            subprocess.Popen(
                self.command(work_dir=work, name=name),
                env={"PATH": os.defpath, "LANG": "C.UTF-8"},
                stdout=output,
                stderr=error,
                text=True,
                start_new_session=True,
            ) as process,
        ):
            timed_out = False
            try:
                while process.poll() is None:
                    if time.monotonic() >= deadline:
                        timed_out = True
                        break
                    relay.handle_request()
            finally:
                self.container.remove(name=name)
                if process.poll() is None:
                    os.killpg(process.pid, signal.SIGKILL)
                    process.wait()
            if timed_out:
                if relay.started:
                    return "Generated policy exceeded its execution time budget"
                raise TimeoutError("Disconnected sandbox startup exceeded its time budget")
            if process.returncode:
                error.seek(0, os.SEEK_END)
                error.seek(max(0, error.tell() - 4000))
                message = error.read()
                if relay.started:
                    return f"Generated policy process failed: {message}"
                raise RuntimeError(f"Disconnected policy execution failed: {message}")
        return None


class RobotRelay(socketserver.UnixStreamServer):
    """Serialize allowed robot requests and enforce the per-option step budget."""

    def __init__(
        self,
        *,
        path: Path,
        bridge: HostBridge,
        max_steps: int,
        trajectory_path: Path | None = None,
    ) -> None:
        self.bridge = bridge
        self.max_steps = max_steps
        self.steps = 0
        self.finished = False
        self.started = False
        self.done = False
        self.error: str | None = None
        self.trajectory_path = trajectory_path
        self._initial_image_recorded = False
        self._last_observation: dict[str, Any] = {}
        self._thread: threading.Thread | None = None
        super().__init__(str(path), RobotRelayHandler)

    def __enter__(self) -> "RobotRelay":
        self._thread = threading.Thread(target=self.serve_forever, daemon=True)
        self._thread.start()
        return self

    def __exit__(self, *args: Any) -> None:
        self.shutdown()
        self.server_close()
        assert self._thread is not None
        self._thread.join(timeout=5)

    def dispatch(self, *, request: dict[str, Any]) -> dict[str, Any]:
        if self.finished:
            raise ValueError("The option execution has already ended")
        operation = request.get("operation")
        if operation == "observe" and set(request) == {"operation"}:
            self.started = True
            observation = self.bridge.observe()
            self._last_observation = observation
            self._record(event={"operation": "observe", "observation": observation})
            return observation
        if operation == "step" and set(request) == {"operation", "action"}:
            self.started = True
            if self.steps >= self.max_steps:
                raise ValueError("Option step budget exhausted")
            action = request["action"]
            if not isinstance(action, dict | list):
                raise ValueError("Action must be an object or array")
            self.steps += 1
            self._record(
                event={"operation": "step_requested", "action": action, "step": self.steps}
            )
            observation = self.bridge.step(action=action)
            self._last_observation = observation
            self._record(
                event={
                    "operation": "step",
                    "action": action,
                    "observation": observation,
                    "step": self.steps,
                }
            )
            return observation
        if (
            operation == "finish"
            and set(request).issubset({"operation", "done", "error"})
            and isinstance(request.get("done"), bool)
        ):
            error = request.get("error")
            if error is not None and not isinstance(error, str):
                raise ValueError("Controller errors must be strings")
            self.finished = True
            self.done = request["done"]
            self.error = error
            self._record(
                event={
                    "operation": "finish",
                    "done": self.done,
                    "steps": self.steps,
                    "error": self.error,
                }
            )
            return {"accepted": True}
        raise ValueError("Only observe, bounded step, and finish requests are available")

    def record_final(self, *, observation: dict[str, Any], error: str | None) -> None:
        self._record(
            event={"operation": "final", "observation": observation, "error": error or self.error}
        )

    def _record(self, *, event: dict[str, Any]) -> None:
        if self.trajectory_path is not None:
            observation = event.get("observation")
            if isinstance(observation, dict):
                keep_images = not self._initial_image_recorded or event["operation"] == "final"
                if keep_images:
                    self._initial_image_recorded = True
                else:
                    event = {
                        **event,
                        "observation": {
                            key: value for key, value in observation.items() if key != "images"
                        },
                    }
            with self.trajectory_path.open("a") as stream:
                stream.write(json.dumps(event, allow_nan=False) + "\n")


class RobotRelayHandler(socketserver.StreamRequestHandler):
    """A length-capped JSON protocol with no deserialization of executable objects."""

    def handle(self) -> None:
        self.connection.settimeout(5)
        response: dict[str, Any]
        try:
            raw = self.rfile.readline(1_000_001)
            if len(raw) > 1_000_000 or not raw.endswith(b"\n"):
                raise ValueError("Invalid robot request length")
            request = json.loads(raw)
            if not isinstance(request, dict):
                raise ValueError("Robot request must be an object")
            assert isinstance(self.server, RobotRelay)
            response = {"result": self.server.dispatch(request=request)}
        except (ValueError, RuntimeError, OSError) as exc:
            response = {"error": str(exc)}
        self.wfile.write(json.dumps(response, allow_nan=False).encode() + b"\n")
